// Hello World
import fs from "node:fs";
import path from "node:path";
import { PNG } from "pngjs";

const inputPath = path.resolve(process.cwd(), "public/brand/prx-logo.png");
const outputPath = path.resolve(process.cwd(), "src/lib/brand/logoPartsData.ts");

if (!fs.existsSync(inputPath)) {
  console.error("Input file not found:", inputPath);
  process.exit(1);
}

fs.createReadStream(inputPath)
  .pipe(new PNG({ filterType: 4 }))
  .on("parsed", function () {
    const origWidth = this.width;
    const origHeight = this.height;
    console.log(`Original image: ${origWidth}x${origHeight}`);

    // Scan columns for alpha > 30
    const colHasPixels = new Array(origWidth).fill(false);
    for (let x = 0; x < origWidth; x++) {
      for (let y = 0; y < origHeight; y++) {
        const idx = (origWidth * y + x) << 2;
        const alpha = this.data[idx + 3];
        if (alpha > 30) {
          colHasPixels[x] = true;
          break;
        }
      }
    }

    // Separate contiguous spans
    const spans = [];
    let inSpan = false;
    let spanStart = 0;

    for (let x = 0; x < origWidth; x++) {
      if (colHasPixels[x] && !inSpan) {
        inSpan = true;
        spanStart = x;
      } else if (!colHasPixels[x] && inSpan) {
        inSpan = false;
        // Require at least a few pixels to avoid single-pixel noise
        if (x - spanStart > 4) {
          spans.push({ start: spanStart, end: x - 1 });
        }
      }
    }
    if (inSpan) {
      spans.push({ start: spanStart, end: origWidth - 1 });
    }

    console.log(`Found ${spans.length} contiguous horizontal spans:`);
    spans.forEach((s, i) => console.log(`Span ${i}: x=[${s.start}, ${s.end}], width=${s.end - s.start + 1}`));

    // Labels for the spans: first is emblem/symbol, then P, R, X
    const labels = ["symbol", "letter-p", "letter-r", "letter-x"];

    const parts = [];

    spans.forEach((span, i) => {
      let minY = origHeight;
      let maxY = 0;

      for (let x = span.start; x <= span.end; x++) {
        for (let y = 0; y < origHeight; y++) {
          const idx = (origWidth * y + x) << 2;
          if (this.data[idx + 3] > 30) {
            if (y < minY) minY = y;
            if (y > maxY) maxY = y;
          }
        }
      }

      const x = span.start;
      const y = minY;
      const w = span.end - span.start + 1;
      const h = maxY - minY + 1;

      // Extract slice into a new transparent PNG
      const slice = new PNG({ width: w, height: h });
      for (let sy = 0; sy < h; sy++) {
        for (let sx = 0; sx < w; sx++) {
          const origIdx = (origWidth * (y + sy) + (x + sx)) << 2;
          const sliceIdx = (w * sy + sx) << 2;

          slice.data[sliceIdx] = this.data[origIdx];
          slice.data[sliceIdx + 1] = this.data[origIdx + 1];
          slice.data[sliceIdx + 2] = this.data[origIdx + 2];
          slice.data[sliceIdx + 3] = this.data[origIdx + 3];
        }
      }

      const buffer = PNG.sync.write(slice);
      const dataUri = `data:image/png;base64,${buffer.toString("base64")}`;
      const id = labels[i] || `part-${i + 1}`;

      parts.push({
        id,
        label: labels[i] || `Parte ${i + 1}`,
        x,
        y,
        w,
        h,
        href: dataUri,
      });

      console.log(`Part ${id}: x=${x}, y=${y}, w=${w}, h=${h}`);
    });

    const fileContent = `// Hello World
// Generated by scripts/slice-logo.js via pngjs column scanning & bounding-box calculation.
// Preserves 100% photographic / chromatic fidelity with isolated vector-animatable slices.

export interface LogoPart {
  id: string;
  label: string;
  x: number;
  y: number;
  w: number;
  h: number;
  href: string;
}

export const LOGO_METADATA = {
  nominalWidth: ${origWidth},
  nominalHeight: ${origHeight},
  viewBox: "0 0 ${origWidth} ${origHeight}",
  subtitle: "EXPERIÊNCIAS QUE CONECTAM GERAÇÕES",
  tagline: "the next pays",
  parts: ${JSON.stringify(parts, null, 2)} as LogoPart[],
} as const;
`;

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, fileContent, "utf-8");
    console.log(`Successfully generated: ${outputPath}`);
  });
